# Generated by Django 6.0.3 on 2026-03-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrosesion',
            options={},
        ),
        migrations.AddField(
            model_name='registrosesion',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='registrosesion',
            name='readiness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrosesion',
            name='rpe',
            field=models.IntegerField(),
        ),
    ]
