# Generated by Django 6.0.3 on 2026-03-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorreg', '0002_alter_registrosesion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosesion',
            name='hrv',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
