# Generated by Django 6.0.3 on 2026-03-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorreg', '0003_registrosesion_hrv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrosesion',
            old_name='hrv',
            new_name='restingHR',
        ),
    ]
